# Generated by Django 5.2.1 on 2025-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbs/', verbose_name='Thumbnail'),
        ),
    ]
