# Generated by Django 5.2.1 on 2025-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0002_alter_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
