# Generated by Django 5.2.1 on 2025-05-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0003_gallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='cover_image',
            field=models.BooleanField(default=False),
        ),
    ]
