# Generated by Django 5.2.1 on 2025-05-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0004_image_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
