# Generated by Django 5.2.1 on 2025-05-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0005_image_description_image_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='zone',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('cert', 'Certificate')], default='gallery', max_length=12),
        ),
    ]
