# Generated by Django 5.2.1 on 2025-05-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0006_gallery_zone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('rank',)},
        ),
    ]
