# Generated by Django 5.2.1 on 2025-05-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0007_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='short_uuid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
