# Generated by Django 5.2.1 on 2025-05-15 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0008_image_short_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='back_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Back File'),
        ),
        migrations.AddField(
            model_name='image',
            name='back_image_alt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='back_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbs/', verbose_name='Back Thumbnail'),
        ),
        migrations.AddField(
            model_name='image',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='h_day',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='image',
            name='h_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='image',
            name='h_year',
            field=models.PositiveSmallIntegerField(default=1320),
        ),
    ]
