# Generated by Django 5.2.1 on 2025-05-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0009_image_back_file_image_back_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='back_description',
            field=models.TextField(blank=True),
        ),
    ]
