# Generated by Django 5.2.1 on 2025-05-15 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0010_image_back_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='h_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='h_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='image',
            name='h_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
