# Generated by Django 5.2.1 on 2025-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0011_alter_image_h_day_alter_image_h_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('rank',)},
        ),
        migrations.AddField(
            model_name='gallery',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
