# Generated by Django 5.2.1 on 2025-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedias', '0012_alter_gallery_options_gallery_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='back_file_local_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='file_local_path',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
